name: Reusable Test

on:
  workflow_call:
    inputs:
      sample_value:
        description: 'A sample value to test'
        required: true
        type: string

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Init
        run: |
          echo "Sample value: ${{ inputs.sample_value }}"

      - name: Install Packages
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          version: 2025.11.10

      - name: Run Tests
        run: |
          uv run pytest
