name: Reusable Test

on:
  workflow_call:
    inputs:
      sample_value:
        description: 'A sample value to test'
        required: true
        type: string

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Init
        run: |
          echo "Sample value: ${{ inputs.sample_value }}"

      - name: Install Packages
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Run Tests
        run: |
          uv run pytest
