name: GitHub Actions Test Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/_reusable-test.yaml
    with:
      sample-value: 'staging'

  deploy:
    needs: test
    uses: ./.github/workflows/_reusable-deploy.yaml
    with:
      environment: staging
